import type { Metadata } from "next";
import "./globals.css";
import Header from "./(components)/layout/Header";
import Footer from "./(components)/layout/Footer";
import Topbar from "./(components)/layout/Topbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
        <Topbar/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
